image: node:latest

stages:
  - build
  - deploy

build-npm:
  stage: build
  script:
    - echo "@ccharz:registry=https://${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
      - .npmrc

  only:
    - main
    - tags

publish-npm:
  stage: deploy
  script:
    - npm publish
  artifacts:
    paths:
      - dist/
      - .npmrc
  only:
    - main
    - tags
